### PR TITLE
Day 1

### PR DESCRIPTION
**Pull request by juliagarant**

### CODE REVIEW

**Review by zainaraza43 — CHANGES_REQUESTED** [review]
First of all I want to congratulate you on doing your first problem! :partying_face: 

There are many duplicates or dead files in these commits I gave you steps on removing these but other than that you should be fine!

**Review by jere-mie — APPROVED** [review]
🚀🚀🚀

**Review by juliagarant — COMMENTED** [review]
Could not figure this out in cmd I'm so frusterated

**Review by prairir — APPROVED** [review]

**Comment by prairir** [comment]
great work @juliagarant 🚀

**Pull request merged**
